services:
  db:
    image: postgres:17
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: road_network
    ports:
      - "5432:5432"

  backend:
    build:
      context: ../backend
    env_file:
    - ../.env
    environment:
      DATABASE_URL: postgresql+psycopg://postgres:postgres@db:5432/road_network
    depends_on:
      - db
    ports:
      - "8000:8000"
